image: androidsdk/android-33

pipelines:
  default:
      - step:
          name: Android Debug Application
          caches:
            - gradle
          script:
            - ./gradlew assembleDebug
            - ./gradlew lint
          artifacts:
            - app/build/outputs/**
            - app/build/reports/**